{% set build = 0 %}
{% set python_min = "3.9" %}
{% set version = "1.1.4-0" %}

package:
  name: iotaa
  version: {{ version.split("-")[0] }}

source:
  url: https://github.com/maddenp/iotaa/archive/refs/tags/v{{ version.split("-")[0] }}-{{ build }}.tar.gz
  sha256: d35c4ba9e8a9726be1e5174c852f0b8c8fb80bec84d11acb874cea3d9bdaad61

build:
  entry_points:
    - iotaa = iotaa:main
  noarch: python
  number: {{ build }}

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - iotaa
  requires:
    - pip
    - pyfakefs
    - pytest
    - python {{ python_min }}
  commands:
    - pip check
    - pytest --pyargs iotaa
    - iotaa --help

about:
  home: https://github.com/maddenp/iotaa
  summary: A Simple Workflow Engine
  description: |
    A simple workflow engine with semantics inspired by Luigi and tasks
    expressed as decorated Python functions
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://github.com/maddenp/iotaa/README.md

extra:
  recipe-maintainers:
    - maddenp
