{% set version = "0.7.3" %}
{% set build = "0" %}

package:
  name: iotaa
  version: {{ version }}

source:
  url: https://github.com/maddenp/iotaa/archive/refs/tags/v{{ version }}-{{ build }}.tar.gz
  sha256: 2670d00a10b9abd25d27d9b20651db2e31428b5a5c5170955ef04b718ba7d62e

build:
  entry_points:
    - iotaa = iotaa:main
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8

test:
  imports:
    - iotaa
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest --pyargs iotaa
    - iotaa --help

about:
  home: https://github.com/maddenp/iotaa
  summary: A Simple Workflow Engine
  description: |
    A simple workflow engine with semantics inspired by Luigi and tasks
    expressed as decorated Python functions
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://github.com/maddenp/iotaa/README.md

extra:
  recipe-maintainers:
    - maddenp
