{% set version = "0.7.2" %}
{% set build = "0" %}

package:
  name: iotaa
  version: {{ version }}

source:
  url: https://github.com/maddenp/iotaa/archive/refs/tags/v{{ version }}-{{ build }}.tar.gz
  sha256: 84702a967782aa94851e038f3361daa969c4d132238d279a750c318961a5c6ab

build:
  entry_points:
    - iotaa = iotaa:main
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8

test:
  imports:
    - iotaa
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest --pyargs iotaa
    - iotaa --help

about:
  home: https://github.com/maddenp/iotaa
  summary: A Tiny Workflow Manager
  description: |
    A tiny workflow manager with semantics inspired by Luigi, with tasks defined
    as decorated Python functions.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://github.com/maddenp/iotaa/README.md

extra:
  recipe-maintainers:
    - maddenp
